// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBamF4VeFaTg6NjN6yfR5UaxRdyUtZAFg4',
    appId: '1:98199896010:web:f1e4ca8ca6792ccb2e9933',
    messagingSenderId: '98199896010',
    projectId: 'firbaseprojectadddelete',
    authDomain: 'firbaseprojectadddelete.firebaseapp.com',
    databaseURL: 'https://firbaseprojectadddelete-default-rtdb.firebaseio.com',
    storageBucket: 'firbaseprojectadddelete.appspot.com',
    measurementId: 'G-Y5NGVSF9YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJfVI6JzOPyNs-_dsp0UJ2Zlwc79Ffb0s',
    appId: '1:98199896010:android:90e4da0c3ce728c22e9933',
    messagingSenderId: '98199896010',
    projectId: 'firbaseprojectadddelete',
    databaseURL: 'https://firbaseprojectadddelete-default-rtdb.firebaseio.com',
    storageBucket: 'firbaseprojectadddelete.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBamF4VeFaTg6NjN6yfR5UaxRdyUtZAFg4',
    appId: '1:98199896010:web:77b9dc445dd7aed72e9933',
    messagingSenderId: '98199896010',
    projectId: 'firbaseprojectadddelete',
    authDomain: 'firbaseprojectadddelete.firebaseapp.com',
    databaseURL: 'https://firbaseprojectadddelete-default-rtdb.firebaseio.com',
    storageBucket: 'firbaseprojectadddelete.appspot.com',
    measurementId: 'G-WG6G8EKBK9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa6_S8lSNf9yFLuPYvUACwU407zmYTAHo',
    appId: '1:98199896010:ios:eedc6abe08260acd2e9933',
    messagingSenderId: '98199896010',
    projectId: 'firbaseprojectadddelete',
    databaseURL: 'https://firbaseprojectadddelete-default-rtdb.firebaseio.com',
    storageBucket: 'firbaseprojectadddelete.appspot.com',
    androidClientId: '98199896010-82k5ssgclh3vptekf82jt1v5uft5lde0.apps.googleusercontent.com',
    iosClientId: '98199896010-gukc38s3fc4jk2j8ibsvc365r8a7ok1g.apps.googleusercontent.com',
    iosBundleId: 'com.shakil.udaanbiz',
  );

}