import 'dart:io';

import 'package:flutter/material.dart';
import 'package:insta_image_viewer/insta_image_viewer.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';
import '../Utils/app_them.dart';
import '../ViewModels/generate_item_list_provider.dart';
import '../ViewModels/user_profile_provider.dart';

class ItemListScreen extends StatefulWidget {
  const ItemListScreen({super.key});

  @override
  State<ItemListScreen> createState() => _ItemListScreenState();
}

class _ItemListScreenState extends State<ItemListScreen> {
  @override
  Widget build(BuildContext context) {
    var billProvider = Provider.of<GenerateItemListProvider>(context, listen: false);
    final GlobalKey shareBillPdfKey = GlobalKey();
    return Scaffold(
        bottomSheet: SizedBox(
          height: MediaQuery.of(context).size.height * 0.1,
          width: MediaQuery.of(context).size.width,
          child: Center(
            child: Container(
              color: AppThem.appBgColor,
              child: Column(
                children: [
                  const Padding(
                    padding: EdgeInsets.only(top: 0.0,),
                    child: Text(
                      "Share Your Pdf:",
                      style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold,color: Colors.white),
                    ),
                  ),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Padding(
                        padding: const EdgeInsets.only(left: 10.0),
                        child: ElevatedButton.icon(
                          onPressed: () {
                            Navigator.pop(context);
                          },
                          icon:  Icon(Icons.download,color: AppThem.appBgColor,),
                          label:  Text("Save",style: TextStyle(color: AppThem.appSecondaryColor),),
                        ),
                      ),
                      Padding(
                        padding: const EdgeInsets.only(right: 10.0),
                        child: ElevatedButton.icon(
                          onPressed: () {
                             billProvider.saveAndSharePDF();
                          },
                          icon:  Icon(Icons.share, color: AppThem.appBgColor,),
                          label:  Text("Share",style: TextStyle(color: AppThem.appSecondaryColor),),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ),
        ),
      body: Consumer<UserProfileProvider>(builder: (context, value, child) {
        value.userProfile.toSet().toList();
        final profile = value.userProfile[0];
        return RepaintBoundary(
          key: billProvider.shareBillPdfKey,
          child: Padding(
            padding: const EdgeInsets.all(10.0),
            child: Center(
              child: Container(
                width: MediaQuery.of(context).size.width * 0.9,
                padding: const EdgeInsets.only(bottom: 10),
                // Adds space at the bottom of the container
                decoration: BoxDecoration(
                  border: Border.all(width: 2, color:AppThem.appBgColor),
                ),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Padding(
                      padding: const EdgeInsets.only(top: 10),
                      child: Text(profile.shopName.toString(),
                        style: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
                      ),
                    ),
                    Text(profile.bankInfo.toString(),style: TextStyle(fontSize: 18),),
                    const SizedBox(height: 5,),
                    Text( billProvider.gstNumCont.text.trim().isNotEmpty
                        ? "GSTIN: ${billProvider.gstNumCont.text.trim()}"
                        : "GSTIN: 09ABCDE1234F1Z5",),
                    const Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Padding(
                          padding: EdgeInsets.only(top: 5),
                          child: Text(
                            "Generated By",
                            style: TextStyle(
                                fontSize: 12, fontWeight: FontWeight.bold),
                          ),
                        ),
                        SizedBox(width: 5),
                        Icon(
                          Icons.local_grocery_store_outlined,
                          color:AppThem.appBgColor,
                          size: 18,
                        ),
                        SizedBox(width: 5),
                        Text(
                          "UdaanBiz",
                          style: TextStyle(fontSize: 12),
                        ),
                      ],
                    ),
                    const SizedBox(height: 5),
                     Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const Padding(
                          padding: EdgeInsets.only(top: 5.0, left: 0.0),
                          child: Text(
                            "Bill Date",
                            style: TextStyle(
                                fontSize: 12, fontWeight: FontWeight.bold),
                          ),
                        ),
                        const SizedBox(width: 5),
                        const Icon(
                          Icons.date_range,
                          color: AppThem.appBgColor,
                          size: 18,
                        ),
                        const SizedBox(width: 5),
                        Text(
                          DateFormat('dd-MM-yyyy').format(DateTime.now()),
                          style: const TextStyle(fontSize: 12),
                        ),
                      ],
                    ),
                    const SizedBox(height: 5),
                    Padding(
                      padding: const EdgeInsets.only(left: 12),
                      child: Row(
                        children: List.generate(32,
                              (index) => Container(
                            margin: const EdgeInsets.symmetric(horizontal: 2,vertical: 5),
                            height: 2,
                            width: 5,
                            color: Colors.black,
                          ),
                        ),
                      ),
                    ),
                    Consumer<GenerateItemListProvider>(builder: (context, value, child) {
                      return
                        SingleChildScrollView(
                          scrollDirection: Axis.horizontal,
                          child: Table(
                            border: TableBorder.all(color: AppThem.appBgColor),
                            defaultVerticalAlignment: TableCellVerticalAlignment.middle,
                            columnWidths: const {
                              0: FixedColumnWidth(40),  // No
                              1: FixedColumnWidth(80), // Product Item
                              2: FixedColumnWidth(50),  // Quantity
                              3: FixedColumnWidth(50),  // Rate
                              4: FixedColumnWidth(70),  // Value
                            },
                            children: [
                              // Table Header
                              const TableRow(
                                decoration: BoxDecoration(color: Colors.white),
                                children: [
                                  Center(
                                      child: Text("No",
                                          style: TextStyle(color: Colors.black, fontSize: 12,fontWeight: FontWeight.bold))),
                                  Center(
                                      child: Text("Product Item",
                                          style: TextStyle(color: Colors.black, fontSize: 12,fontWeight: FontWeight.bold))),
                                  Center(
                                      child: Text("Quantity",
                                          style: TextStyle(color: Colors.black, fontSize: 12,fontWeight: FontWeight.bold))),
                                  Center(
                                      child: Text("Rate(₹)",
                                          style: TextStyle(color: Colors.black, fontSize: 12,fontWeight: FontWeight.bold))),
                                  Center(
                                      child: Text("Amount(₹)",
                                          style: TextStyle(color: Colors.black, fontSize: 12,fontWeight: FontWeight.bold))),
                                ],
                              ),
                              ...List.generate(value.visibleProducts, (index) {
                                if (value.nameCtr[index].text.isEmpty) {
                                  return const TableRow(children: [
                                    SizedBox(), SizedBox(), SizedBox(), SizedBox(), SizedBox()
                                  ]);
                                }

                                return TableRow(
                                  children: [
                                    Center(
                                      child: Text(
                                        (index + 1).toString(),
                                        style: const TextStyle(fontSize: 10),
                                      ),
                                    ),
                                    Center(
                                      child: Text(
                                        value.nameCtr[index].text,
                                        style: const TextStyle(fontSize: 10),
                                      ),
                                    ),
                                    Center(
                                      child: Text(
                                "${value.qtyCtr[index].text} ${value.selectedUnit[index].split('(').first.trim()}",

                                style: const TextStyle(fontSize: 10),
                                      ),
                                    ),
                                    Center(
                                      child: Text(
                                        value.rateCtr[index].text,
                                        style: const TextStyle(fontSize: 10),
                                      ),
                                    ),
                                    Center(
                                      child: Text(
                                        "${value.amount[index].toStringAsFixed(2)}",
                                        style: const TextStyle(fontSize: 10),
                                      ),
                                    ),
                                  ],
                                );
                              }),
                            ],
                          ),
                        )
                      ;
                    },),
                     const SizedBox(height: 10,),
                     const Padding(
                      padding: EdgeInsets.symmetric(horizontal: 10),
                      child: Divider(
                        color: Colors.black,
                        thickness: 1,
                        indent: 0,
                        endIndent: 0,
                      ),
                    ),
                     Row(
                      children: [
                        const Padding(
                          padding: EdgeInsets.only(left: 10, top: 5),
                          child: Text("Total Amount"),
                        ),
                        Padding(
                          padding: const EdgeInsets.only(left: 150, top: 5),
                          child: Text("₹ ${billProvider.totalAmount.toString()}"),
                        ),
                      ],
                    ),
                    Row(
                      children: [
                        Padding(
                          padding: const EdgeInsets.only(left: 10, top: 5),
                          child: InstaImageViewer(
                            child: SizedBox(
                              height: 50,
                              width: 50,
                              child: profile.qrImage != null
                                  ? Image.file(File(profile.qrImage!),
                                  fit: BoxFit.cover)
                                  : const Image(
                                  image: AssetImage(
                                      "assets/images/shakil_upi_scaner.jpg")),
                            ),
                          ),
                        ),
                         Padding(
                          padding: const EdgeInsets.only(left: 12, top: 2),
                          child:Text("प्रिय ग्राहक ${billProvider.custemerNameCont.text.trim()}, "
                              "${billProvider.holidayNameCont.text.toString()} के पावन अवसर\nपर आपको एवं आपके परिवार को हार्दिक शुभकामनाएँ।\n"
                              "यह बिल कंप्यूटर द्वारा तैयार किया गया है।\n किसी भी प्रकार की त्रुटि होने पर कृपया तुरंत सूचित करें।\n भूल-चूक लेनी-देनी। "
                              "धन्यवाद! ${profile.shopName}",style: TextStyle(fontSize: 8.0,),),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
          ),
        );
      },),
    );
  }
}
