import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:insta_image_viewer/insta_image_viewer.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';
import '../Utils/app_them.dart';
import '../ViewModels/transition_history_provider.dart';
import '../ViewModels/user_profile_provider.dart';
import '../ViewModels/user_provider.dart';

class AdminTemplateListScreen extends StatefulWidget {
  final int? id;
  const AdminTemplateListScreen({super.key, required this.id});

  @override
  State<AdminTemplateListScreen> createState() => _AdminTemplateListScreenState();
}

class _AdminTemplateListScreenState extends State<AdminTemplateListScreen> {
  late UserProvider userProvider;
  late UserProfileProvider userProfileProvider;
  late TransitionHistoryProvider creditProvider;

  @override
  void initState() {
    super.initState();
    userProvider = Provider.of<UserProvider>(context, listen: false);
    super.initState();
    userProvider.showData();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      Provider.of<UserProfileProvider>(context, listen: false)
          .showProfileData();

      creditProvider =
          Provider.of<TransitionHistoryProvider>(context, listen: false);
      creditProvider.usersId = widget.id!;
      creditProvider.showAmountTransition();});
  }

  @override
  Widget build(BuildContext context) {
    var   profileData = Provider.of<UserProfileProvider>(context, listen: false);
    return
      Scaffold(
        appBar: AppBar(backgroundColor: AppThem.appBgColor,
          title: const Text("Select Template",style: TextStyle(color: Colors.white),),),
        body:Consumer<UserProfileProvider>(builder: (context, value, child) {
          value.userProfile.toSet().toList();
          final profile = value.userProfile[0];
          return ListView(
            scrollDirection: Axis.horizontal,
            children: [
              Padding(
                padding: const EdgeInsets.all(10.0),
                child: Center(
                  child: Container(
                    height: MediaQuery.of(context).size.height * 0.6,
                    width: MediaQuery.of(context).size.width * 0.9,
                    padding: const EdgeInsets.only(bottom: 20),
                    // Adds space at the bottom of the container
                    decoration: BoxDecoration(
                      border: Border.all(width: 2, color: Colors.black),
                    ),
                    child: Column(
                      children: [
                        Padding(
                          padding: const EdgeInsets.only(top: 10),
                          child: Text(profile.shopName.toString(),
                            style: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
                          ),
                        ),
                        Text(profile.bankInfo.toString()),
                        const Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(top: 10),
                              child: Text(
                                "Generated By",
                                style: TextStyle(
                                    fontSize: 12, fontWeight: FontWeight.bold),
                              ),
                            ),
                            SizedBox(width: 5),
                            Icon(
                              Icons.local_grocery_store_outlined,
                              color: Colors.black,
                              size: 18,
                            ),
                            SizedBox(width: 5),
                            Text(
                              "UdaanBiz",
                              style: TextStyle(fontSize: 12),
                            ),
                          ],
                        ),
                        const SizedBox(height: 5),
                        const Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(top: 10.0, left: 0.0),
                              child: Text(
                                "Bill Date",
                                style: TextStyle(
                                    fontSize: 12, fontWeight: FontWeight.bold),
                              ),
                            ),
                            SizedBox(width: 5),
                            Icon(
                              Icons.date_range,
                              color: Colors.black,
                              size: 18,
                            ),
                            SizedBox(width: 5),
                            Text(
                              "22/12/2024",
                              style: TextStyle(fontSize: 12),
                            ),
                          ],
                        ),
                        const SizedBox(height: 5),
                        Padding(
                          padding: const EdgeInsets.only(left: 12),
                          child: Row(
                            children: List.generate(
                              32,
                                  (index) => Container(
                                margin: const EdgeInsets.symmetric(horizontal: 2,vertical: 5),
                                height: 2,
                                width: 5,
                                color: Colors.black,
                              ),
                            ),
                          ),
                        ),
                        Expanded(
                          child:Consumer<TransitionHistoryProvider>(builder: (context, value, child) {
                            value.transitionList.toSet().toList();
                            return
                              SingleChildScrollView(
                                scrollDirection: Axis.horizontal,
                                child: Table(
                                  border: TableBorder.all(color: Colors.blue),
                                  defaultVerticalAlignment: TableCellVerticalAlignment.middle,
                                  columnWidths: const {
                                    0: FixedColumnWidth(40),  // No
                                    1: FixedColumnWidth(80), // Product Item
                                    2: FixedColumnWidth(50),  // Quantity
                                    3: FixedColumnWidth(50),  // Rate
                                    4: FixedColumnWidth(70),  // Value
                                  },
                                  children: [
                                    // Table Header
                                    const TableRow(
                                      decoration: BoxDecoration(color: Colors.white),
                                      children: [
                                        Center(
                                            child: Text("No",
                                                style: TextStyle(color: Colors.black, fontSize: 12,fontWeight: FontWeight.bold))),
                                        Center(
                                            child: Text("Product Item",
                                                style: TextStyle(color: Colors.black, fontSize: 12,fontWeight: FontWeight.bold))),
                                        Center(
                                            child: Text("Quantity",
                                                style: TextStyle(color: Colors.black, fontSize: 12,fontWeight: FontWeight.bold))),
                                        Center(
                                            child: Text("Rate",
                                                style: TextStyle(color: Colors.black, fontSize: 12,fontWeight: FontWeight.bold))),
                                        Center(
                                            child: Text("Amount",
                                                style: TextStyle(color: Colors.black, fontSize: 12,fontWeight: FontWeight.bold))),
                                      ],
                                    ),

                                    // Table Rows - replace with your actual list
                                    ...List.generate(15, (index) {
                                      return TableRow(
                                        children: [
                                          Center(
                                              child: Text((index + 1).toString(),
                                                  style: const TextStyle(fontSize: 10))),
                                          const Center(
                                              child: Text("productName" ?? "---",
                                                  style: TextStyle(fontSize: 10))),
                                          const Center(
                                              child: Text("5 KG",
                                                  style: TextStyle(fontSize: 10))),
                                          const Center(
                                              child: Text("28",
                                                  style: TextStyle(fontSize: 10))),
                                          const Center(
                                              child: Text("140",
                                                  style: TextStyle(fontSize: 10))),
                                        ],
                                      );
                                    }),
                                  ],
                                ),
                              )
                            ;
                          },),
                        ),
                        const Padding(
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: Divider(
                            color: Colors.black,
                            thickness: 1,
                            indent: 0,
                            endIndent: 0,
                          ),
                        ),
                        const Row(
                          children: [
                            Padding(
                              padding: EdgeInsets.only(left: 10, top: 5),
                              child: Text("Total Amount"),
                            ),
                            Padding(
                              padding: EdgeInsets.only(left: 150, top: 5),
                              child: Text("75000/"),
                            ),
                          ],
                        ),
                        Row(
                          children: [
                            Padding(
                              padding: const EdgeInsets.only(left: 10, top: 5),
                              child: InstaImageViewer(
                                child: SizedBox(
                                  height: 40,
                                  width: 40,
                                  child: Image.asset(
                                    "assets/images/shakil_upi_scaner.jpg",
                                  ),
                                ),
                              ),
                            ),
                            const Padding(
                              padding: EdgeInsets.only(left: 12, top: 2),
                              child:Text("प्रिय ग्राहक, कृपया सुनिश्चित करें कि भुगतान  \n  10 दिनों के भीतर कर दिया जाए, ताकि  \n क्रेडिट सेवाएं बिना किसी रुकावट के जारी रह सकें। \n धन्यवाद!",style: TextStyle(fontSize: 8.0,),),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Padding(
                padding: const EdgeInsets.all(10.0),
                child: Center(
                  child: Container(
                    height: MediaQuery.of(context).size.height * 0.6,
                    width: MediaQuery.of(context).size.width * 0.9,
                    padding: const EdgeInsets.only(bottom: 20),
                    // Adds space at the bottom of the container
                    decoration: BoxDecoration(
                      border: Border.all(width: 2, color: Colors.green),
                    ),
                    child: Column(
                      children: [
                         Padding(
                          padding: const EdgeInsets.only(top: 10),
                          child: Text(profile.shopName.toString(),
                            style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
                          ),
                        ),
                         const SizedBox(height: 2),
                        Text(profile.bankInfo.toString()),
                        const Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(top: 12),
                              child: Text(
                                "Generated By",
                                style: TextStyle(
                                    fontSize: 12, fontWeight: FontWeight.bold),
                              ),
                            ),
                            SizedBox(width: 5),
                            CircleAvatar(radius: 10,backgroundImage: AssetImage("assets/images/udaan_biz_logo (1).png"),),
                            SizedBox(width: 5),
                            Text(
                              "UdaanBiz",
                              style: TextStyle(fontSize: 12),
                            ),
                          ],
                        ),
                        const SizedBox(height: 10),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            const Padding(
                              padding: EdgeInsets.only(top: 10.0, left: 0.0),
                              child: Text(
                                "Bill Date",
                                style: TextStyle(
                                    fontSize: 12, fontWeight: FontWeight.bold),
                              ),
                            ),
                            const SizedBox(width: 5),
                            const Icon(
                              Icons.date_range,
                              color: Colors.green,
                              size: 18,
                            ),
                            const SizedBox(width: 5),
                            Text(DateFormat('dd-MM-yyyy').format(DateTime.now(),),style: const TextStyle(fontSize: 12),),
                          ],
                        ),
                        const SizedBox(height: 10),
                        const Padding(
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: Divider(
                            color: Colors.green,
                            thickness: 2,
                            indent: 0,
                            endIndent: 0,
                          ),
                        ),
                        const Row(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(left: 8.0, top: 5.0),
                              child: Text('Product Item 1'),
                            ),
                            Padding(
                              padding: EdgeInsets.only(left: 140.0, top: 5.0),
                              child: Text('Rate (₹)'),
                            ),
                          ],
                        ),
                        const SizedBox(height: 10),
                        Padding(
                          padding: const EdgeInsets.only(left: 10),
                          child: Row(
                            children: List.generate(
                              32,
                                  (index) => Container(
                                margin: const EdgeInsets.symmetric(horizontal: 2),
                                height: 2,
                                width: 5,
                                color: Colors.green,
                              ),
                            ),
                          ),
                        ),
                        Expanded(
                          child:Consumer<TransitionHistoryProvider>(builder: (context, value, child) {
                            value.transitionList.toSet().toList();
                            return ListView.builder(
                              itemCount:value.transitionList.length ,

                              itemBuilder: (context, index){
                                var item = value.transitionList[index];
                                bool isReceived = item.isReceived == 'isReceive';
                                return isReceived ?
                                Row(
                                  children: [
                                    Padding(
                                      padding: const EdgeInsets.only(left: 5, top: 10),
                                      child: Text("Product Item ${index + 1}"),
                                    ),
                                    Padding(
                                      padding: const EdgeInsets.only(left: 160, top: 10),
                                      child: Text("${item.loanedMoney}/"),
                                    ),
                                  ],
                                ): const CircularProgressIndicator();
                              },
                            );
                          },),
                        ),
                        const Padding(
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: Divider(
                            color: Colors.green,
                            thickness: 1,
                            indent: 0,
                            endIndent: 0,
                          ),
                        ),
                        const Row(
                          children: [
                            Padding(
                              padding: EdgeInsets.only(left: 10, top: 5),
                              child: Text("Total Amount"),
                            ),
                            Padding(
                              padding: EdgeInsets.only(left: 150, top: 5),
                              child: Text("75000/"),
                            ),
                          ],
                        ),
                        Row(
                          children: [
                            Padding(
                              padding: const EdgeInsets.only(left: 10, top: 5),
                              child: InstaImageViewer(
                                child:
                                SizedBox(
                                  height: 40,
                                  width: 40,
                                  child: profile.qrImage != null
                                      ? Image.file(File(profile.qrImage!),
                                      fit: BoxFit.cover)
                                      : const Image(
                                      image: AssetImage(
                                          "assets/images/shakil_upi_scaner.jpg")),
                                ),
                              ),
                            ),
                            Padding(
                              padding: const EdgeInsets.only(left: 180, top: 5),
                              child:SizedBox(
                                height: 40,
                                width: 40,
                                child: profile.qrImage != null
                                    ? Image.file(File(profile.profileImage!),
                                    fit: BoxFit.cover)
                                    : const Image(
                                    image: AssetImage(
                                        "assets/images/shakil_upi_scaner.jpg")),
                              ),
                            ),
                          ],
                        ),
                        Text(profile.phone.toString())
                      ],
                    ),
                  ),
                ),
              ),
              Padding(
                padding: const EdgeInsets.all(10.0),
                child: Center(
                  child: Container(
                    height: MediaQuery.of(context).size.height * 0.6,
                    width: MediaQuery.of(context).size.width * 0.9,
                    padding: const EdgeInsets.only(bottom: 20),
                    // Adds space at the bottom of the container
                    decoration: BoxDecoration(
                      border: Border.all(width: 2, color: Colors.black),
                    ),
                    child: Column(
                      children: [
                         Padding(
                          padding: const EdgeInsets.only(top: 10),
                          child: Text(profile.shopName.toString(),
                            style: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
                          ),
                        ),
                        Text(profile.bankInfo.toString()),
                        const Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(top: 10),
                              child: Text(
                                "Generated By",
                                style: TextStyle(
                                    fontSize: 12, fontWeight: FontWeight.bold),
                              ),
                            ),
                            SizedBox(width: 5),
                            Icon(
                              Icons.local_grocery_store_outlined,
                              color: Colors.black,
                              size: 18,
                            ),
                            SizedBox(width: 5),
                            Text(
                              "UdaanBiz",
                              style: TextStyle(fontSize: 12),
                            ),
                          ],
                        ),
                        const SizedBox(height: 5),
                        const Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(top: 10.0, left: 0.0),
                              child: Text(
                                "Bill Date",
                                style: TextStyle(
                                    fontSize: 12, fontWeight: FontWeight.bold),
                              ),
                            ),
                            SizedBox(width: 5),
                            Icon(
                              Icons.date_range,
                              color: Colors.black,
                              size: 18,
                            ),
                            SizedBox(width: 5),
                            Text(
                              "22/12/2024",
                              style: TextStyle(fontSize: 12),
                            ),
                          ],
                        ),
                        const SizedBox(height: 5),
                        Padding(
                          padding: const EdgeInsets.only(left: 12),
                          child: Row(
                            children: List.generate(
                              32,
                                  (index) => Container(
                                margin: const EdgeInsets.symmetric(horizontal: 2,vertical: 5),
                                height: 2,
                                width: 5,
                                color: Colors.black,
                              ),
                            ),
                          ),
                        ),
                        Expanded(
                          child:Consumer<TransitionHistoryProvider>(builder: (context, value, child) {
                            value.transitionList.toSet().toList();
                            return
                              SingleChildScrollView(
                                scrollDirection: Axis.horizontal,
                                child: Table(
                                  border: TableBorder.all(color: Colors.blue),
                                  defaultVerticalAlignment: TableCellVerticalAlignment.middle,
                                  columnWidths: const {
                                    0: FixedColumnWidth(40),  // No
                                    1: FixedColumnWidth(80), // Product Item
                                    2: FixedColumnWidth(50),  // Quantity
                                    3: FixedColumnWidth(50),  // Rate
                                    4: FixedColumnWidth(70),  // Value
                                  },
                                  children: [
                                    // Table Header
                                    const TableRow(
                                      decoration: BoxDecoration(color: Colors.white),
                                      children: [
                                        Center(
                                            child: Text("No",
                                                style: TextStyle(color: Colors.black, fontSize: 12,fontWeight: FontWeight.bold))),
                                        Center(
                                            child: Text("Product Item",
                                                style: TextStyle(color: Colors.black, fontSize: 12,fontWeight: FontWeight.bold))),
                                        Center(
                                            child: Text("Quantity",
                                                style: TextStyle(color: Colors.black, fontSize: 12,fontWeight: FontWeight.bold))),
                                        Center(
                                            child: Text("Rate",
                                                style: TextStyle(color: Colors.black, fontSize: 12,fontWeight: FontWeight.bold))),
                                        Center(
                                            child: Text("Amount",
                                                style: TextStyle(color: Colors.black, fontSize: 12,fontWeight: FontWeight.bold))),
                                      ],
                                    ),

                                    // Table Rows - replace with your actual list
                                    ...List.generate(15, (index) {
                                      return TableRow(
                                        children: [
                                          Center(
                                              child: Text((index + 1).toString(),
                                                  style: const TextStyle(fontSize: 10))),
                                          const Center(
                                              child: Text("productName" ?? "---",
                                                  style: TextStyle(fontSize: 10))),
                                          const Center(
                                              child: Text("5 L",
                                                  style: TextStyle(fontSize: 10))),
                                          const Center(
                                              child: Text("28",
                                                  style: TextStyle(fontSize: 10))),
                                          const Center(
                                              child: Text("140",
                                                  style: TextStyle(fontSize: 10))),
                                        ],
                                      );
                                    }),
                                  ],
                                ),
                              )
                            ;
                          },),
                        ),
                        const Padding(
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: Divider(
                            color: Colors.black,
                            thickness: 1,
                            indent: 0,
                            endIndent: 0,
                          ),
                        ),
                        const Row(
                          children: [
                            Padding(
                              padding: EdgeInsets.only(left: 10, top: 5),
                              child: Text("Total Amount"),
                            ),
                            Padding(
                              padding: EdgeInsets.only(left: 150, top: 5),
                              child: Text("75000/"),
                            ),
                          ],
                        ),
                        Row(
                          children: [
                            Padding(
                              padding: const EdgeInsets.only(left: 10, top: 5),
                              child: InstaImageViewer(
                                child: SizedBox(
                                  height: 40,
                                  width: 40,
                                  child: Image.asset(
                                    "assets/images/shakil_upi_scaner.jpg",
                                  ),
                                ),
                              ),
                            ),
                            const Padding(
                              padding: EdgeInsets.only(left: 12, top: 2),
                              child:Text("प्रिय ग्राहक, कृपया सुनिश्चित करें कि भुगतान  \n  10 दिनों के भीतर कर दिया जाए, ताकि  \n क्रेडिट सेवाएं बिना किसी रुकावट के जारी रह सकें। \n धन्यवाद!",style: TextStyle(fontSize: 8.0,),),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Padding(
                padding:  const EdgeInsets.all(10.0),
                child: Center(
                  child: Container(
                    height: 500,
                    width: 400,
                    padding: const EdgeInsets.only(bottom: 20),  // Adds space at the bottom of the container
                    decoration: BoxDecoration(
                      border: Border.all(width: 2, color: Colors.green),
                    ),
                    child: Column(
                      children: [
                        const Padding(
                          padding: EdgeInsets.only(top: 10),
                          child: Text(
                            "ABC Store",
                            style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                          ),
                        ),
                        const SizedBox(height: 10),
                        const Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(top: 10),
                              child: Text(
                                "Generated By",
                                style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold),
                              ),
                            ),
                            SizedBox(width: 5),
                            Icon(
                              Icons.local_grocery_store_outlined,
                              color: Colors.green,
                              size: 18,
                            ),
                            SizedBox(width: 5),
                            Text(
                              "UdaanBiz",
                              style: TextStyle(fontSize: 12),
                            ),
                          ],
                        ),
                        const SizedBox(height: 10),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            const Padding(
                              padding: EdgeInsets.only(top: 10.0, left: 0.0),
                              child: Text(
                                "Bill Date",
                                style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold),
                              ),
                            ),
                            const SizedBox(width: 5),
                            const Icon(
                              Icons.date_range,
                              color: Colors.green,
                              size: 18,
                            ),
                            const SizedBox(width: 5),
                            // DateFormat('dd-MM-yyyy').format(DateTime.now()
                            Text(DateFormat('dd-MM-yyyy').format(DateTime.now(),),style: const TextStyle(fontSize: 12),
                            ),

                          ],
                        ),
                        const SizedBox(height: 10),
                        const Padding(
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: Divider(
                            color: Colors.green,
                            thickness: 2,
                            indent: 0,
                            endIndent: 0,
                          ),
                        ),
                        const Row(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(left: 8.0, top: 5.0),
                              child: Text('Product Item 1'),
                            ),
                            Padding(
                              padding: EdgeInsets.only(left: 160.0, top: 5.0),
                              child: Text('Rate (₹)'),
                            ),
                          ],
                        ),
                        const SizedBox(height: 10),
                        Padding(
                          padding: const EdgeInsets.symmetric(horizontal: 10),
                          child: Row(
                            children: List.generate(
                              35,
                                  (index) => Container(
                                margin: const EdgeInsets.symmetric(horizontal: 2),
                                height: 2,
                                width: 5,
                                color: Colors.green,
                              ),
                            ),
                          ),
                        ),
                        Expanded(
                          child:Consumer<TransitionHistoryProvider>(builder: (context, value, child) {
                            value.transitionList.toSet().toList();
                            return ListView.builder(
                              itemCount: 5,
                              itemBuilder: (context, index) => Row(
                                children: [
                                  Padding(
                                    padding: const EdgeInsets.only(left: 5, top: 10),
                                    child: Text("Product Item ${index + 1}"),
                                  ),
                                  const Padding(
                                    padding: EdgeInsets.only(left: 160, top: 10),
                                    child: Text("1500/"),
                                  ),
                                ],
                              ),
                            );
                          },),
                        ),
                        const Padding(
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: Divider(
                            color: Colors.green,
                            thickness: 1,
                            indent: 0,
                            endIndent: 0,
                          ),
                        ),
                        const Row(
                          children: [
                            Padding(
                              padding: EdgeInsets.only(left: 10, top: 5),
                              child: Text("Total Amount"),
                            ),
                            Padding(
                              padding: EdgeInsets.only(left: 150, top: 5),
                              child: Text("75000/"),
                            ),
                          ],
                        ),
                        Row(
                          children: [
                            Padding(
                              padding: const EdgeInsets.only(left: 10, top: 5),
                              child: InstaImageViewer(
                                child: SizedBox(
                                  height: 40,
                                  width: 40,
                                  child: Image.asset(
                                    "assets/images/shakil_upi_scaner.jpg",
                                  ),
                                ),
                              ),
                            ),
                            Padding(
                              padding: const EdgeInsets.only(left: 170, top: 5),
                              child: IconButton(onPressed: () {

                              }, icon: const Icon(Icons.send,color: Colors.green,size: 30,)),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Padding(
                padding:  const EdgeInsets.all(10.0),
                child: Center(
                  child: Container(
                    height: 500,
                    width: 400,
                    padding: const EdgeInsets.only(bottom: 20),
                    decoration: BoxDecoration(
                      border: Border.all(width: 2, color: Colors.green),
                    ),
                    child: Column(
                      children: [
                        const Padding(
                          padding: EdgeInsets.only(top: 10),
                          child: Text(
                            "ABC Store",
                            style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                          ),
                        ),
                        const SizedBox(height: 10),
                        const Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(top: 10),
                              child: Text(
                                "Generated By",
                                style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold),
                              ),
                            ),
                            SizedBox(width: 5),
                            Icon(
                              Icons.local_grocery_store_outlined,
                              color: Colors.green,
                              size: 18,
                            ),
                            SizedBox(width: 5),
                            Text(
                              "UdaanBiz",
                              style: TextStyle(fontSize: 12),
                            ),
                          ],
                        ),
                        const SizedBox(height: 10),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            const Padding(
                              padding: EdgeInsets.only(top: 10.0, left: 0.0),
                              child: Text(
                                "Bill Date",
                                style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold),
                              ),
                            ),
                            const SizedBox(width: 5),
                            const Icon(
                              Icons.date_range,
                              color: Colors.green,
                              size: 18,
                            ),
                            const SizedBox(width: 5),
                            Text(DateFormat('dd-MM-yyyy').format(DateTime.now(),),style: const TextStyle(fontSize: 12),),
                          ],
                        ),
                        const SizedBox(height: 10),
                        const Padding(
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: Divider(
                            color: Colors.green,
                            thickness: 2,
                            indent: 0,
                            endIndent: 0,
                          ),
                        ),
                        const Row(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(left: 8.0, top: 5.0),
                              child: Text('Product Item 1'),
                            ),
                            Padding(
                              padding: EdgeInsets.only(left: 160.0, top: 5.0),
                              child: Text('Rate (₹)'),
                            ),
                          ],
                        ),
                        const SizedBox(height: 10),
                        Padding(
                          padding: const EdgeInsets.symmetric(horizontal: 10),
                          child: Row(
                            children: List.generate(
                              35,
                                  (index) => Container(
                                margin: const EdgeInsets.symmetric(horizontal: 2),
                                height: 2,
                                width: 5,
                                color: Colors.green,
                              ),
                            ),
                          ),
                        ),
                        Expanded(
                          child:Consumer<TransitionHistoryProvider>(builder: (context, value, child) {
                            value.transitionList.toSet().toList();
                            return ListView.builder(
                              itemCount: 5,
                              itemBuilder: (context, index) => Row(
                                children: [
                                  Padding(
                                    padding: const EdgeInsets.only(left: 5, top: 10),
                                    child: Text("Product Item ${index + 1}"),
                                  ),
                                  const Padding(
                                    padding: EdgeInsets.only(left: 160, top: 10),
                                    child: Text("1500/"),
                                  ),
                                ],
                              ),
                            );
                          },),
                        ),
                        const Padding(
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: Divider(
                            color: Colors.green,
                            thickness: 1,
                            indent: 0,
                            endIndent: 0,
                          ),
                        ),
                        const Row(
                          children: [
                            Padding(
                              padding: EdgeInsets.only(left: 10, top: 5),
                              child: Text("Total Amount"),
                            ),
                            Padding(
                              padding: EdgeInsets.only(left: 150, top: 5),
                              child: Text("75000/"),
                            ),
                          ],
                        ),
                        Row(
                          children: [
                            Padding(
                              padding: const EdgeInsets.only(left: 10, top: 5),
                              child: InstaImageViewer(
                                child: SizedBox(
                                  height: 40,
                                  width: 40,
                                  child: Image.asset(
                                    "assets/images/shakil_upi_scaner.jpg",
                                  ),
                                ),
                              ),
                            ),
                            Padding(
                              padding: const EdgeInsets.only(left: 170, top: 5),
                              child: IconButton(onPressed: () {

                              }, icon: const Icon(Icons.send,color: Colors.green,size: 30,)),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              )
            ],
          );
        },),
      );
  }

  void datePiker() async{
    DateTime? datePicker = await showDatePicker(context: context,
        firstDate: DateTime(2020),
        initialDate: DateTime.now(),
        lastDate: DateTime.now());
    if(datePicker != null){
      if (kDebugMode) {
        print("date selected ${datePicker.day}");
      }
    }
  }
}